### ISSUE TITLE
Feat changer le fond d'écran

### ISSUE THREAD

**Issue by Ptitet** [Ptitet/Questionnaire-culture#4]
Juste appliquer un filtre sur le body : 
```css
body {
    filter: invert(100%)
}
```

Possibilité d'amélioration : slider pour contrôler le degré d'inversion
